### ISSUE TITLE
Branding + graphics of PDF report

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#5]
Development of branding, font and graphics within the PDF report.

**Comment by lowwintersun** [comment]
NB, project title is: SEEMS 'Simple Energy Efficiency Measures'

**Comment by AppSynergy** [comment]
I thought it was "Home Energy Health Check"?

**Comment by AppSynergy** [comment]
So, what wants to go where, anyone have any thoughts?

I'm looking through the Brand Book, there's plenty in terms of logos, box layouts and colors in there.

[264_Brand_Book1.pdf](https://github.com/carboncoop/home-energy-health-check/files/1427020/264_Brand_Book1.pdf)

Current view is based roughly on the original paper version.

[20170706 YOUR HOME ENERGY REPORT.pdf](https://github.com/carboncoop/home-energy-health-check/files/1427035/20170706.YOUR.HOME.ENERGY.REPORT.pdf)

In there there's some useful images of insulation, fans, alarms, laundry etc. Shall we add these in? Is there e.g. an image library I can draw from?

**Comment by lowwintersun** [comment]
Cool - I think we should keep it pretty simple as per the more detailed assessments we do - obviously with the changed colours. 

[Uploading CC08_JCR_MHEP Report.pdf…]()

I can create an image library, will be later today though. 

On the name: this implementation is called: SEEMS 'Simple Energy Efficiency Measures'
...we want this to be a generic tool for use in other places, by other organisations, hence "Home Energy Health Check" is the generic title of the tool.

**Comment by lowwintersun** [comment]
Immediate priority for this is to remove the 'to do: branding messages' as it more or less works in this format at the moment.

**Comment by lowwintersun** [comment]
PEC are reviewing the PDF and will get back with comments ASAP.

**Comment by lowwintersun** [comment]
Adam, just so you can see, PEC and I have been working up some improvements to the PDF layout. They've suggested some options for the front page and I've worked up the internal pages. I'm waiting approval from them on the internal pages. Would it help for me to annotate the internal one with sizes, measurements and fonts etc? 

[PEC Improved Layout.pdf](https://github.com/carboncoop/home-energy-health-check/files/1462185/PEC.Improved.Layout.pdf)

[Energy assessment report front cover mock up (1).pdf](https://github.com/carboncoop/home-energy-health-check/files/1462186/Energy.assessment.report.front.cover.mock.up.1.pdf)

**Comment by AppSynergy** [comment]
ok great.

> some options for the front page

I like the green one, though the blue "mm"s clash a bit. They're all similar enough to build, anyway.

> Would it help for me to annotate 

Certainly, cheers.

**Comment by lowwintersun** [comment]
OK, on the front page I agree with you, the green is nice but clashes, my favourite is the second one, the blue background. I've asked for sign off on this from the client. 

I will annotate a print out of the other stuff and email it to you later today. 

J

**Comment by lowwintersun** [comment]
OK, I've annotated my layout. It's in InDesign, hence it's in points and mm - hopefully this can convert to your plugin - but very happy to look at stuff and comment. 

[20171114112801.pdf](https://github.com/carboncoop/home-energy-health-check/files/1470517/20171114112801.pdf)

Also, they've gone with the second front page layout - ie the one with blue. They are working up an image to fit.

**Comment by AppSynergy** [comment]
It's simply CSS, so I'm converting with:  `10pt ~= 13px, 10mm ~= 38px`.

**Comment by AppSynergy** [comment]
There's one major issue - we want most pages to have a 17/22mm page margin, but the cover sheet to be flush to the page, and I don't think I can process it in that way.

+ So the front page might have to have margins too, or:
+ We remove the margins and add them in manually where required. This is easy for left and right, but is tricker for top and bottom because you don't know exactly where the pages are going to break (though some of them e.g. end of section are forced).

With images in the markdown, they need some little wrappers like so:

````
<span class="float-right pb-4 pl-4">
![](https://i.imgur.com/HfR9G10.jpg?2)
</span>
````
(that's float right, padding bottom and padding left) in order to look right.

Otherwise, mostly done I think. Can I go into maintenance mode and make a new release at some point? (There's some libraries that need updates, so might be a few minutes..)

**Comment by lowwintersun** [comment]
I think its probably better to put margins on the front page given the choice. Do you want to do maintenance mode this evening? Let me know and I will issue them with a warning. Will the update effect previous PDFs created? If so I will warn them of that too.

**Comment by AppSynergy** [comment]
I'm not sure I'll have time this evening, might be better to find a 20 minute* window tomorrow when no-one's in the field.

\* to be safe? probably more like 5. It's only because there's some big library updates queued, so I want to get them in. Any further tweaks to pdf styles can be done without going to maintenance.

> Will the update effect previous PDFs created?

Nope, if they're already emailed out then they're out of our influence. 

When you hit submit, a new pdf is created each time, so it'll affect pdfs emailed from the moment the code is released onwards.

The pdf preview button generates a new pdf on the fly each time (but it's not saved to disc) so that'll always reflect the latest code.

**Comment by lowwintersun** [comment]
Great, I'll let them know it will be down at 5pm today for an hour or so. Here's a graphic they sent in case it's of use.

[608_PEC_House_Heat_V2.pdf](https://github.com/carboncoop/home-energy-health-check/files/1477891/608_PEC_House_Heat_V2.pdf)

**Comment by AppSynergy** [comment]
That's the image to go in the centre of the front page, right?

Is there somewhere I can get a copy of the PEC logo on a transparent bg? 
Preferably with different colored `mm` - maybe white or yellow?

**Comment by AppSynergy** [comment]
`rc-0.4` released, bringing the latest changes here up to date.

**Comment by lowwintersun** [comment]
Have asked for feedback on the implemented PDF - there might be minor tweaks and then we can close.

**Comment by lowwintersun** [comment]
Final change to PDF - remove blue boxes at top and bottom of front page. 

![screenshot-2017-12-8 your home energy report seem - simple energy efficiency measures - 76](https://user-images.githubusercontent.com/7352302/33763358-136524a4-dc08-11e7-945c-9711cea29ed5.png)

**Comment by AppSynergy** [comment]
Cleaner, and better for printing out!
